services:
  - type: web
    name: sigma-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false